"""全局配置（兼容旧代码）"""
from config_manager import load_config, get_config

# 加载配置
load_config()

# ========== YOLO模型配置 ==========
MODEL_PATH = get_config('MODEL_PATH')
CROP_SIZE = get_config('CROP_SIZE')
CONF_THRESHOLD = get_config('CONF_THRESHOLD')
IOU_THRESHOLD = get_config('IOU_THRESHOLD')
TARGET_CLASS_NAMES = get_config('TARGET_CLASS_NAMES')

# ========== 瞄准精度优化 ==========
AIM_POINTS = get_config('AIM_POINTS')

# ========== 目标切换控制 ==========
MIN_TARGET_LOCK_FRAMES = get_config('MIN_TARGET_LOCK_FRAMES')
TARGET_SWITCH_THRESHOLD = get_config('TARGET_SWITCH_THRESHOLD')
TARGET_IDENTITY_DISTANCE = get_config('TARGET_IDENTITY_DISTANCE')

# ========== 后坐力补偿配置 ==========
RECOIL_COMPENSATION_MODE = get_config('RECOIL_COMPENSATION_MODE')
RECOIL_DETECTION_THRESHOLD = get_config('RECOIL_DETECTION_THRESHOLD')
RECOIL_RESPONSE_MULTIPLIER = get_config('RECOIL_RESPONSE_MULTIPLIER')

# ========== 智能阈值控制 ==========
ENABLE_SMART_THRESHOLD = get_config('ENABLE_SMART_THRESHOLD')
MOVEMENT_THRESHOLD_PIXELS = get_config('MOVEMENT_THRESHOLD_PIXELS')
INITIAL_LOCK_THRESHOLD = get_config('INITIAL_LOCK_THRESHOLD')
ARRIVAL_THRESHOLD_ENTER = get_config('ARRIVAL_THRESHOLD_ENTER')
ARRIVAL_THRESHOLD_EXIT = get_config('ARRIVAL_THRESHOLD_EXIT')
MIN_SEND_INTERVAL_MS = get_config('MIN_SEND_INTERVAL_MS')
STABLE_FRAMES_REQUIRED = get_config('STABLE_FRAMES_REQUIRED')
COOLDOWN_AFTER_ARRIVAL_MS = get_config('COOLDOWN_AFTER_ARRIVAL_MS')

# ========== 鼠标控制配置 ==========
GAME_MODE = get_config('GAME_MODE')
GAME_DEAD_ZONE = get_config('GAME_DEAD_ZONE')
GAME_DAMPING_FACTOR = get_config('GAME_DAMPING_FACTOR')
MOUSE_ARRIVAL_THRESHOLD = get_config('MOUSE_ARRIVAL_THRESHOLD')
MOUSE_PROPORTIONAL_FACTOR = get_config('MOUSE_PROPORTIONAL_FACTOR')
MOUSE_MAX_PIXELS_PER_STEP = get_config('MOUSE_MAX_PIXELS_PER_STEP')
DEFAULT_DELAY_MS_PER_STEP = get_config('DEFAULT_DELAY_MS_PER_STEP')

# ========== 驱动路径 ==========
DRIVER_PATH = get_config('DRIVER_PATH')

# ========== 目标跟踪配置 ==========
MAX_LOST_FRAMES = get_config('MAX_LOST_FRAMES')
DISTANCE_WEIGHT = get_config('DISTANCE_WEIGHT')
COMMAND_UPDATE_THRESHOLD = get_config('COMMAND_UPDATE_THRESHOLD')

# ========== 鼠标按钮标志 ==========
APP_MOUSE_NO_BUTTON = get_config('APP_MOUSE_NO_BUTTON')
APP_MOUSE_LEFT_DOWN = get_config('APP_MOUSE_LEFT_DOWN')
APP_MOUSE_LEFT_UP = get_config('APP_MOUSE_LEFT_UP')
APP_MOUSE_RIGHT_DOWN = get_config('APP_MOUSE_RIGHT_DOWN')
APP_MOUSE_RIGHT_UP = get_config('APP_MOUSE_RIGHT_UP')
APP_MOUSE_MIDDLE_DOWN = get_config('APP_MOUSE_MIDDLE_DOWN')
APP_MOUSE_MIDDLE_UP = get_config('APP_MOUSE_MIDDLE_UP')

# ========== IOCTL请求码 ==========
MOUSE_REQUEST = get_config('MOUSE_REQUEST')
